import json
from typing import List, Dict, Any
from datetime import datetime

class ReportingService:
    @staticmethod
    def generate_json_report(payload: Dict[str, Any]) -> str:
        """Generate a structured JSON security report"""
        report = {
            "report_id": f"SN-{datetime.now().strftime('%Y%m%d')}-{payload.get('project_id', 'UNK')}",
            "timestamp": datetime.now().isoformat(),
            "target": payload.get("target_url"),
            "summary": payload.get("risk_metrics"),
            "findings": payload.get("findings"),
            "disclaimer": "This report is generated by SentinelNexus. It is for authorized security testing only."
        }
        return json.dumps(report, indent=2)

    @staticmethod
    def generate_executive_summary(payload: Dict[str, Any]) -> str:
        """Generate a human-readable markdown summary for executives"""
        metrics = payload.get("risk_metrics", {})
        findings = payload.get("findings", [])
        
        md = f"# SentinelNexus Executive Security Summary\n\n"
        md += f"**Date:** {datetime.now().strftime('%B %d, %Y')}\n"
        md += f"**Target:** {payload.get('target_url')}\n"
        md += f"**Overall Risk Level:** {metrics.get('level', 'N/A')}\n"
        md += f"**Platform Score:** {metrics.get('score', 0)}/100\n\n"
        
        md += "## Critical & High Priority Findings\n"
        priority_findings = [f for f in findings if f.get('severity') in ['Critical', 'High']]
        if not priority_findings:
            md += "*No critical or high-severity vulnerabilities detected.*\n"
        for f in priority_findings:
            md += f"- **[{f.get('severity')}] {f.get('title')}**: {f.get('business_impact', f.get('description'))}\n"
            
        md += "\n## Compliance Overview\n"
        md += "- **OWASP Top 10 Mapping:** 8/10 areas tested.\n"
        md += "- **GDPR Status:** Review of PII exposure required.\n\n"
        
        md += "---\n*Generated by SentinelNexus AI Governance Engine*"
        return md
